#!/usr/bin/env bash
# Isaac Sim (Windows プロセス) <-> nav2 コンテナ (WSL2 の podman machine) を DDS で
# 繋ぐための Fast DDS プロファイルを吐く。**両側に同じものを渡すこと**
# (FASTRTPS_DEFAULT_PROFILES_FILE)。片側だけでは繋がらない。
#
#   bash simulator/container/make_fastdds_mirrored.sh 91 > /tmp/fastdds_mirrored.xml
#
# 前提として `%USERPROFILE%\.wslconfig` に networkingMode=mirrored が要る。既定の
# NAT では WSL VM が別サブネットに居るので、コンテナの host ネットワーク指定は
# 「WSL VM のホスト」にしかならず、Isaac のトピックが**エラーも出ないまま一度も
# 見えない**。README の「Isaac と nav2 を繋ぐ (Windows + WSL)」を参照。
#
# 静的な XML にできないのは、ユニキャストのピアを**ポートまで書く**必要があり、
# それが ROS_DOMAIN_ID で決まるため (7400 + 250*domain + 10 + 2*participant_id)。
#
# 中身の理由。どれも 2026-08-20 の実測で必要と分かった。
#
#   * SHM を使わない。**入れると discovery が黙って止まる。** `--ipc host` の
#     コンテナで participant が 2 つ以上立つと、エラーも警告も出ないまま
#     互いを見つけられない (Fast DDS 2.6 は SHM が使えなくても UDP へ落ちない)。
#     Windows 側の Isaac はもっと露骨で、**DDS のポートを 1 つも開かないまま上がる**。
#     そもそも Windows と Linux で SHM セグメントは共有できないので使えない。
#     **代償としてコンテナ内のノード同士も UDP になる** —— pi4_sim ハーネス
#     (container/fastdds_local.xml、SHM 併用) とは通信経路が違う。純粋な Pi4
#     再現を測るならあちらを使うこと。
#   * マルチキャストに頼らずユニキャストのピアを並べる。mirrored では
#     **マルチキャストが一度も届かない** (同じコンテナ内の 2 ノード間ですら)。
#     ポートを書かない locator は participant 0〜4 にしか広がらず、nav2 は
#     participant を 10 個以上立てるので足りない。ここでは 0〜31 を並べる。
#   * UDP の maxMessageSize を 1400 に絞る。既定 (65500) だと LaserScan
#     (Example_Rotary_2D は 0.1 度刻み = 3600 点で約 29KB) が IP フラグメントに
#     なり、**Windows -> WSL の境界で全部落ちる**。`ros2 topic list` には出るし
#     `/odom` や `/tf` のような小さいメッセージは 70Hz で流れるので、
#     **「繋がっているのに /scan_raw だけ来ない」**という分かりにくい形で失敗する
#     (sample-lost だけが上がり続ける)。RTPS 側で刻めば 1 フラグメントが 1 データ
#     グラムに収まって通る。
set -o pipefail

DOMAIN=${1:-${ROS_DOMAIN_ID:-0}}
PEERS=${2:-32}                      # 並べる participant の数
BASE=$((7400 + 250 * DOMAIN + 10))  # metatraffic unicast の participant 0 のポート

cat <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by container/make_fastdds_mirrored.sh (domain=$DOMAIN peers=$PEERS) -->
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <transport_descriptors>
    <transport_descriptor>
      <transport_id>udp_mirrored</transport_id>
      <type>UDPv4</type>
      <sendBufferSize>8388608</sendBufferSize>
      <receiveBufferSize>8388608</receiveBufferSize>
      <maxMessageSize>1400</maxMessageSize>
    </transport_descriptor>
  </transport_descriptors>
  <participant profile_name="mirrored_participant" is_default_profile="true">
    <rtps>
      <userTransports>
        <transport_id>udp_mirrored</transport_id>
      </userTransports>
      <useBuiltinTransports>false</useBuiltinTransports>
      <builtin>
        <initialPeersList>
XML
i=0
while [ "$i" -lt "$PEERS" ]; do
    echo "          <locator><udpv4><address>127.0.0.1</address><port>$((BASE + 2 * i))</port></udpv4></locator>"
    i=$((i + 1))
done
cat <<XML
        </initialPeersList>
      </builtin>
    </rtps>
  </participant>
</profiles>
XML
